name: Build

# Note that push and pull-request builds are automatically
# now skipped by GitHub if
# [skip ci], [ci skip], [no ci], [skip actions], or [actions skip]
# are in the commit message. We don't need to check for this ourselves.

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  bigtest:
    name: build (${{ matrix.python-version }}, ${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform:
          - { name: "windows", os: "windows-latest", shell: "pwsh" }
          - { name: "linux", os: "ubuntu-latest", shell: "bash -l {0}" }
          - { name: "macos", os: "macos-latest", shell: "bash -l {0}" }
        exclude:
          # Exclude all but the latest Python from all
          # but Linux
          - platform:
              { name: "macos", os: "macos-latest", shell: "bash -l {0}" }
            python-version: "3.12"  # MacOS can't run 3.12 yet... We want 3.10 and 3.11
          - platform: { name: "windows", os: "windows-latest", shell: "pwsh" }
            python-version: "3.10"
          - platform: { name: "windows", os: "windows-latest", shell: "pwsh" }
            python-version: "3.11"
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    env:
      SIRE_DONT_PHONEHOME: 1
      SIRE_SILENT_PHONEHOME: 1
      REPO: "${{ github.event.pull_request.head.repo.full_name || github.repository }}"
    steps:
      #
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sire_build
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true
      #
      - name: Install the latest version of sire
        run: mamba install -y -c "openbiosim/label/test" sire
      #
      - name: Clone the big tests repo
        run: git clone https://github.com/${{ env.REPO }} tests
      #
      - name: Run the tests
        run: python tests/run_tests.py
      #
      - name: Install pytest
        run: mamba install pytest
      - name: Install kcombu_bss
        run: mamba install -c "openbiosim/label/dev" kcombu_bss
      - name: Clone BioSimSpace (we use the latest devel version)
        run: git clone https://github.com/openbiosim/biosimspace
      - name: Install BioSimSpace
        run: pip install .
        working-directory: biosimspace/python
      - name: Run BioSimSpace tests
        run: pytest tests
        working-directory: biosimspace
